# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image: gitpod/workspace-postgres

tasks:
  - init: pip install -r requirements.txt
    command: echo this is a test mate
